export const ActionType = {
  USER_FETCH: "USER_FETCH",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_LOGOUT: "USER_LOGOUT",
  CREATE_USER: "CREATE USER",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",

  INCREMENT:"INCREMENT",
  DECREMENT:"DECREMENT"
};
